/**
 * TypeScript types for Calendar feature.
 *
 * Mirrors backend Pydantic schemas.
 */

// ========== Enums ==========

export enum CalendarProvider {
  GOOGLE = 'google',
  MICROSOFT = 'microsoft',
}

export enum CalendarOperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  FIND = 'find',
}

export enum ClarificationReason {
  MULTIPLE_EVENTS = 'multiple_events',
  MULTIPLE_PROVIDERS = 'multiple_providers',
  MISSING_INFORMATION = 'missing_information',
  AMBIGUOUS_TIME = 'ambiguous_time',
}

// ========== Commands ==========

export interface CalendarCommand {
  action: CalendarOperationType;
  provider?: CalendarProvider;

  // Create/Update fields
  title?: string;
  title_autogenerated?: boolean;
  starts_at?: string; // ISO 8601
  ends_at?: string; // ISO 8601
  timezone?: string;
  attendees?: string[];
  description?: string;
  add_video_conference?: boolean;

  // Update/Delete fields
  event_id?: string;
  search_title?: string;
  search_range_start?: string;
  search_range_end?: string;

  // List/Find fields
  range_start?: string;
  range_end?: string;
  query?: string;

  // Meta
  requires_confirmation?: boolean;
  confidence_score?: number;
}

export interface ClarificationQuestion {
  reason: ClarificationReason;
  message: string;
  options?: Array<{ label: string; value: string }>;
  show_calendar_modal?: boolean;
  partial_command?: CalendarCommand;
}

export interface CalendarParseRequest {
  text: string;
  timezone?: string;
  now_iso?: string;
  assistant_id?: string;
  provider_preference?: CalendarProvider;
}

export interface CalendarParseResponse {
  success: boolean;
  command?: CalendarCommand;
  clarification?: ClarificationQuestion;
  error?: string;
}

// ========== Execution ==========

export interface CalendarExecuteRequest {
  command: CalendarCommand;
  assistant_id?: string;
  skip_confirmation?: boolean;
}

export interface EventSummary {
  id: string;
  title: string;
  starts_at: string; // ISO 8601
  ends_at: string; // ISO 8601
  timezone: string;
  provider: CalendarProvider;
  calendar_id: string;
  attendees: string[];
  video_conference_link?: string;
  html_link?: string;
  description?: string;
}

export interface CalendarResult {
  success: boolean;
  operation: CalendarOperationType;
  provider?: CalendarProvider;
  event?: EventSummary;
  events?: EventSummary[];
  message: string;
  error?: string;
}

// ========== Providers ==========

export interface ProviderInfo {
  provider: CalendarProvider;
  nango_connection_id: string;
  is_active: boolean;
  user_email?: string;
  connected_at: string; // ISO 8601
}

export interface ProvidersListResponse {
  providers: ProviderInfo[];
  has_google: boolean;
  has_microsoft: boolean;
}

// ========== Events List ==========

export interface CalendarEventsRequest {
  range_start: string; // ISO 8601
  range_end: string; // ISO 8601
  provider?: CalendarProvider;
  query?: string;
}

export interface CalendarEventsResponse {
  events: EventSummary[];
  range_start: string;
  range_end: string;
  providers_queried: CalendarProvider[];
}

// ========== Availability ==========

export interface BusySlot {
  starts_at: string;
  ends_at: string;
  event_title?: string;
}

export interface FreeSlot {
  starts_at: string;
  ends_at: string;
  score?: number;
}

export interface AvailabilityRequest {
  range_start: string;
  range_end: string;
  provider?: CalendarProvider;
  slot_duration_minutes?: number;
}

export interface AvailabilityResponse {
  busy_slots: BusySlot[];
  free_slots: FreeSlot[];
  range_start: string;
  range_end: string;
}
