/**
 * Create event dialog - Quick event creation form.
 *
 * Features:
 * - Pre-filled from draft (if slot clicked)
 * - Select provider
 * - Add video conference checkbox
 * - Attendees (comma-separated emails)
 */

import { useState, useEffect } from 'react';
import { useMutation } from '@tanstack/react-query';
import { format } from 'date-fns';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { toast } from 'sonner';
import { calendarApi } from '@/api/calendar';
import { useCalendarStore } from '@/stores/calendarStore';
import type { ProviderInfo } from '@/types/calendar';
import { CalendarProvider, CalendarOperationType } from '@/types/calendar';

interface Props {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
  providers: ProviderInfo[];
}

export function CreateEventDialog({ open, onClose, onSuccess, providers }: Props) {
  const { draftEvent, setDraftEvent } = useCalendarStore();

  // Form state
  const [title, setTitle] = useState('');
  const [startDate, setStartDate] = useState('');
  const [startTime, setStartTime] = useState('');
  const [endDate, setEndDate] = useState('');
  const [endTime, setEndTime] = useState('');
  const [description, setDescription] = useState('');
  const [attendees, setAttendees] = useState('');
  const [addVideo, setAddVideo] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState<CalendarProvider | ''>(
    providers[0]?.provider || ''
  );

  // Pre-fill from draft
  useEffect(() => {
    if (draftEvent && open) {
      const start = draftEvent.starts_at;
      const end = draftEvent.ends_at;

      setStartDate(format(start, 'yyyy-MM-dd'));
      setStartTime(format(start, 'HH:mm'));
      setEndDate(format(end, 'yyyy-MM-dd'));
      setEndTime(format(end, 'HH:mm'));
    }
  }, [draftEvent, open]);

  // Create event mutation
  const createMutation = useMutation({
    mutationFn: async () => {
      if (!selectedProvider) {
        throw new Error('Sélectionne un calendrier');
      }

      const starts_at = new Date(`${startDate}T${startTime}`).toISOString();
      const ends_at = new Date(`${endDate}T${endTime}`).toISOString();

      const result = await calendarApi.execute({
        command: {
          action: CalendarOperationType.CREATE,
          provider: selectedProvider,
          title: title || 'Rendez-vous',
          title_autogenerated: !title,
          starts_at,
          ends_at,
          timezone: 'Europe/Paris',
          attendees: attendees ? attendees.split(',').map((e) => e.trim()) : [],
          description: description || undefined,
          add_video_conference: addVideo,
        },
      });

      return result;
    },
    onSuccess: (result) => {
      if (result.success) {
        toast.success(result.message);
        onSuccess();
        handleReset();
      } else {
        toast.error(result.message || 'Erreur lors de la création');
      }
    },
    onError: (error: Error) => {
      toast.error(error.message || 'Erreur lors de la création');
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    if (!startDate || !startTime || !endDate || !endTime) {
      toast.error('Date et heure obligatoires');
      return;
    }

    createMutation.mutate();
  };

  const handleReset = () => {
    setTitle('');
    setDescription('');
    setAttendees('');
    setAddVideo(false);
    setDraftEvent(null);
  };

  const handleClose = () => {
    handleReset();
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(open) => !open && handleClose()}>
      <DialogContent className="max-w-2xl">
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>Nouvel événement</DialogTitle>
            <DialogDescription>Crée un événement dans ton calendrier</DialogDescription>
          </DialogHeader>

          <div className="space-y-4 py-4">
            {/* Provider */}
            {providers.length > 1 && (
              <div className="space-y-2">
                <Label htmlFor="provider">Calendrier</Label>
                <Select
                  value={selectedProvider}
                  onValueChange={(val) => setSelectedProvider(val as CalendarProvider)}
                >
                  <SelectTrigger id="provider">
                    <SelectValue placeholder="Sélectionne un calendrier" />
                  </SelectTrigger>
                  <SelectContent>
                    {providers.map((p) => (
                      <SelectItem key={p.provider} value={p.provider}>
                        {p.provider === CalendarProvider.GOOGLE ? 'Google Calendar' : 'Microsoft Outlook'}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}

            {/* Title */}
            <div className="space-y-2">
              <Label htmlFor="title">Titre</Label>
              <Input
                id="title"
                placeholder="Ex: Réunion équipe"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>

            {/* Start Date/Time */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="startDate">Date début</Label>
                <Input
                  id="startDate"
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="startTime">Heure début</Label>
                <Input
                  id="startTime"
                  type="time"
                  value={startTime}
                  onChange={(e) => setStartTime(e.target.value)}
                  required
                />
              </div>
            </div>

            {/* End Date/Time */}
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="endDate">Date fin</Label>
                <Input
                  id="endDate"
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  required
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="endTime">Heure fin</Label>
                <Input
                  id="endTime"
                  type="time"
                  value={endTime}
                  onChange={(e) => setEndTime(e.target.value)}
                  required
                />
              </div>
            </div>

            {/* Attendees */}
            <div className="space-y-2">
              <Label htmlFor="attendees">Participants (optionnel)</Label>
              <Input
                id="attendees"
                placeholder="email1@example.com, email2@example.com"
                value={attendees}
                onChange={(e) => setAttendees(e.target.value)}
              />
              <p className="text-xs text-muted-foreground">
                Sépare les emails par des virgules
              </p>
            </div>

            {/* Description */}
            <div className="space-y-2">
              <Label htmlFor="description">Description (optionnel)</Label>
              <Textarea
                id="description"
                placeholder="Détails de l'événement..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
              />
            </div>

            {/* Video checkbox */}
            <div className="flex items-center space-x-2">
              <Checkbox id="addVideo" checked={addVideo} onCheckedChange={(checked) => setAddVideo(!!checked)} />
              <Label htmlFor="addVideo" className="cursor-pointer">
                Ajouter un lien visio ({selectedProvider === CalendarProvider.GOOGLE ? 'Google Meet' : 'Microsoft Teams'})
              </Label>
            </div>
          </div>

          <DialogFooter>
            <Button type="button" variant="outline" onClick={handleClose}>
              Annuler
            </Button>
            <Button type="submit" disabled={createMutation.isPending}>
              {createMutation.isPending ? 'Création...' : 'Créer'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
